apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ include "myapp.fullname" . }}
  labels: {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels: {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "myapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        #imagePullPolicy: {{ .Values.image.pullPolicy }}
        # === A. 把 Secret 注成环境变量（推荐、最简单）===
       # {{- if .Values.secret.inject.envFrom }}
       # envFrom:
       #   - secretRef:
       #       name: {{ .Values.secret.name | default "myapp-db" }}
       # {{- end }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        readinessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet:
            path: /
            port: http
          initialDelaySeconds: 10
          periodSeconds: 10
        resources: {{- toYaml .Values.resources | nindent 10 }}
