{{- if .Values.rollouts.enabled }}
apiVersion: argoproj.io/v1alpha1
kind: Rollout
metadata:
  name: {{ include "myapp.fullname" . }}
  labels: {{- include "myapp.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    canary:
      canaryService: {{ include "myapp.fullname" . }}-canary
      stableService: {{ include "myapp.fullname" . }}
      trafficRouting:
        nginx:
          stableIngress: {{ include "myapp.fullname" . }}   # 由 Rollouts 自动创建/管理 canary ingress
          additionalIngressAnnotations:
            nginx.ingress.kubernetes.io/canary-by-header: "{{ .Values.rollouts.canary.header }}"
      steps:
{{- toYaml .Values.rollouts.canary.steps | nindent 8 }}
  selector:
    matchLabels: {{- include "myapp.selectorLabels" . | nindent 6 }}
  template:
    metadata:
      labels: {{- include "myapp.selectorLabels" . | nindent 8 }}
    spec:
      containers:
      - name: myapp
        image: "{{ .Values.image.repository }}:{{ .Values.image.tag }}"
        imagePullPolicy: {{ .Values.image.pullPolicy }}
        ports:
        - containerPort: {{ .Values.service.targetPort }}
          name: http
        readinessProbe:
          httpGet: { path: /, port: http }
          initialDelaySeconds: 3
          periodSeconds: 5
        livenessProbe:
          httpGet: { path: /, port: http }
          initialDelaySeconds: 10
          periodSeconds: 10
        resources: {{- toYaml .Values.resources | nindent 10 }}
{{- end }}
