apiVersion: v1
kind: Namespace
metadata:
  name: jenkins
---
apiVersion: v1
kind: ServiceAccount
metadata:
  name: jenkins-agent
  namespace: jenkins
  annotations:
    # 用 Terraform 模块输出替换这里：
    eks.amazonaws.com/role-arn: arn:aws:iam::160885250897:role/project-eks-dev-eks-JenkinsAgentECR