apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cluster-autoscaler
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://kubernetes.github.io/autoscaler
    chart: cluster-autoscaler
    targetRevision: 9.32.0              # 对应 CA 1.29.x，可固定具体版本
    helm:
      values: |
        cloudProvider: aws
        awsRegion: us-east-1
        autoDiscovery:
          clusterName: project-eks-dev-eks
        serviceAccount:
          create: true
          name: cluster-autoscaler-aws-cluster-autoscaler
          annotations:
            eks.amazonaws.com/role-arn: arn:aws:iam::160885250897:role/project-eks-dev-eks-ClusterAutoscaler

        customArgs:
          - --cloud-provider=aws
          - --aws-region=us-east-1
          - --node-group-auto-discovery=asg:tag=k8s.io/cluster-autoscaler/enabled,k8s.io/cluster-autoscaler/project-eks-dev-eks
          - --address=0.0.0.0
          - --balance-similar-node-groups=true
          - --skip-nodes-with-local-storage=false
          - --skip-nodes-with-system-pods=false
          - --v=4

        image:
          repository: registry.k8s.io/autoscaling/cluster-autoscaler
          tag: v1.32.0  

        rbac:
          create: true

        podAnnotations:
          cluster-autoscaler.kubernetes.io/safe-to-evict: "false"

        resources:
          limits:   { cpu: 200m, memory: 300Mi }
          requests: { cpu: 100m, memory: 200Mi }
  destination:
    server: https://kubernetes.default.svc
    namespace: kube-system
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
