replicaCount: 2

image:
  repository: "160885250897.dkr.ecr.us-east-1.amazonaws.com/myapp"
  tag: ""     # CI 会用 --set image.tag=xxxx 注入
  pullPolicy: IfNotPresent

service:
  type: ClusterIP
  port: 80
  targetPort: 8080

ingress:
  enabled: true
  className: nginx
  host: ""
  path: /
  tls: false       # Day 2 验证阶段先不启用 TLS

resources:
  requests:
    cpu: "50m"
    memory: "64Mi"
  limits:
    cpu: "200m"
    memory: "256Mi"

podDisruptionBudget:
  enabled: true
  minAvailable: 1

serviceAccount:
  create: true          # 默认创建 SA
  name: ""              # 为空则用模板里的默认命名
  automount: true
  annotations: {}

autoscaling:
  enabled: false
  minReplicas: 2
  maxReplicas: 5
  # 建议只开一个指标即可；需要时再打开
  targetCPUUtilizationPercentage: 60
  # targetMemoryUtilizationPercentage: 70