replicaCount: 2
ingress:
  host: myapp.dev
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
ingress:
  enabled: true
  className: nginx
  host: myapp.dev
  path: /
  tls: false
  extraAnnotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-exempt: "127.0.0.1"
image:
<<<<<<< HEAD
  tag: 0e4faa50
=======
  tag: 190dda9

secret:
  name: myapp-secret        # 这要与 ExternalSecret.spec.target.name 一致
  inject:
    envFrom: true           # 选 true：注入所有 key 为 env
    singleKeys: false       # 选 true：只注入示例里的 DB_PASSWORD
    volume: false           # 选 true：以文件方式挂载
  mountPath: /etc/secrets   # 仅当 volume=true 时生效
  reloadOnChange: true     # 你若装了 reloader，可设 true 自动滚动
>>>>>>> 74d525d (update charts)
