replicaCount: 2
ingress:
  host: myapp.dev
autoscaling:
  enabled: true
  minReplicas: 2
  maxReplicas: 10
  targetCPUUtilizationPercentage: 10
ingress:
  enabled: true
  className: nginx
  host: myapp.dev
  path: /
  tls: false
  extraAnnotations:
    nginx.ingress.kubernetes.io/ssl-redirect: "false"
    nginx.ingress.kubernetes.io/limit-rps: "20"
    nginx.ingress.kubernetes.io/limit-burst-multiplier: "3"
    nginx.ingress.kubernetes.io/limit-exempt: "127.0.0.1"
image:
  tag: 0e4faa50
