apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-staging
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/DaqulaLin/aws-eks-devops-blueprint.git
    targetRevision: main
    path: charts/myapp
    helm:
      valueFiles:
        - values-staging.yaml
      parameters:
        - name: image.repository
          value: 160885250897.dkr.ecr.us-east-1.amazonaws.com/myapp
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: staging
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
