apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: myapp-dev
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/<YOUR_ORG>/<YOUR_REPO>.git
    targetRevision: main
    path: charts/myapp
    helm:
      valueFiles:
        - values-dev.yaml
      parameters:
        - name: image.repository
          value: <ACCOUNT_ID>.dkr.ecr.us-east-1.amazonaws.com/myapp
        - name: image.tag
          value: latest
  destination:
    server: https://kubernetes.default.svc
    namespace: dev
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
