apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: myapp-success-rate
  namespace: dev
spec:
  args:
    - name: ingress
  metrics:
    - name: error-rate
      interval: 30s
      count: 8
      # 连续出错多少次后判定该 metric 失败，可按需调整
      consecutiveErrorLimit: 10
      # 允许的错误率阈值：< 1% 通过
      successCondition: asFloat(result[0]) < 0.01
      # 连续达到 failureLimit 次失败则中止发布
      failureLimit: 3
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          # 错误率 = 5xx 请求速率 / 总请求速率
          # 兼容两种指标名，任选其一有数据即可；无数据时用 vector(0) 兜底，分母用 clamp_min 防止除零
          query: |
            (sum(rate(nginx_ingress_controller_requests_total{ingress="{{args.ingress}}",status=~"5.."}[1m]))
             or sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",status=~"5.."}[1m]))
             or vector(0))
            /
            clamp_min(
              (sum(rate(nginx_ingress_controller_requests_total{ingress="{{args.ingress}}"}[1m]))
               or sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}"}[1m]))
               or vector(0)),
              0.000001
            )
