apiVersion: argoproj.io/v1alpha1
kind: AnalysisTemplate
metadata:
  name: myapp-success-rate
  namespace: dev
spec:
  args:
    - name: ingress
  metrics:
    - name: error-rate
      interval: 30s
      count: 4
      successCondition: result < 0.01
      failureLimit: 1
      provider:
        prometheus:
          address: http://kube-prometheus-stack-prometheus.monitoring.svc.cluster.local:9090
          query: |
            sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}",status=~"5.."}[1m]))
            /
            sum(rate(nginx_ingress_controller_requests{ingress="{{args.ingress}}"}[1m]))

