apiVersion: v1
kind: ServiceAccount
metadata:
  name: dev-viewer
  namespace: dev
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-view-binding
  namespace: dev
subjects:
- kind: ServiceAccount
  name: dev-viewer
  namespace: dev
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
