apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: addons-root
  namespace: argocd
  finalizers: [resources-finalizer.argocd.argoproj.io]
spec:
  project: default
  source:
    repoURL: https://github.com/DaqulaLin/aws-eks-devops-blueprint.git
    targetRevision: main
    path: manifests/addons/cluster-autoscaler
    directory:
      recurse: true
  destination:
    server: https://kubernetes.default.svc
    namespace: argocd
  syncPolicy:
    automated:
      prune: true
      selfHeal: true