apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-admin
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: ns-admin
  namespace: prod
rules:
- apiGroups: ["", "apps", "batch", "extensions", "autoscaling", "networking.k8s.io"]
  resources: ["*"]
  verbs: ["*"]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-admin-binding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: prod-admin
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: ns-admin
