apiVersion: v1
kind: ServiceAccount
metadata:
  name: prod-viewer
  namespace: prod
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: ns-view-binding
  namespace: prod
subjects:
- kind: ServiceAccount
  name: prod-viewer
  namespace: prod
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: view
